// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CriarForncedorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.addArguments("--headless");
    chromeOptions.addArguments("--no-sandbox");
    driver = new ChromeDriver(chromeOptions);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void criarForncedor() {
    driver.get("https://app-13-106-47405.ide.cronapp.io/#/home");
    driver.manage().window().setSize(new Dimension(1153, 656));
    driver.findElement(By.cssSelector(".dropdown:nth-child(6) > .dropdown-toggle > span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".dropdown-menu > li:nth-child(3) span:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#bc75 > .k-icon")).click();
    driver.findElement(By.id("textinput-cnpj")).click();
    driver.findElement(By.id("textinput-cnpj")).sendKeys("50.737.766/0002-02");
    driver.findElement(By.id("textinput-nome")).click();
    driver.findElement(By.id("textinput-nome")).sendKeys("Techne Engenharia e Sistemas LTDA");
    driver.findElement(By.id("textinput-telefone")).click();
    driver.findElement(By.id("textinput-telefone")).sendKeys("(71) 99999-9999");
    driver.findElement(By.id("textinput-email")).click();
    driver.findElement(By.id("textinput-email")).sendKeys("techne@teste.com");
    driver.findElement(By.id("btn_crud_post41107")).click();
  }
}
