// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CriarClienteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.addArguments("--headless");
    chromeOptions.addArguments("--no-sandbox");
    driver = new ChromeDriver(chromeOptions);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void criarCliente() {
    driver.get("https://app-13-106-47405.ide.cronapp.io/#/home");
    driver.manage().window().setSize(new Dimension(1045, 647));
    driver.findElement(By.cssSelector(".dropdown:nth-child(6) > .dropdown-toggle")).click();
    driver.findElement(By.cssSelector(".open li:nth-child(2) > a")).click();
    driver.findElement(By.id("b85f")).click();
    driver.findElement(By.id("textinput-nome")).click();
    driver.findElement(By.id("textinput-nome")).sendKeys("Pedro Lima");
    driver.findElement(By.id("textinput-cpf")).click();
    driver.findElement(By.id("textinput-cpf")).sendKeys("068.603.865-76");
    driver.findElement(By.id("textinput-telefone")).click();
    driver.findElement(By.id("textinput-telefone")).sendKeys("(71) 99632-6837");
    driver.findElement(By.id("textinput-email")).click();
    driver.findElement(By.id("textinput-email")).sendKeys("pedro.lima@cronapp.io");
    driver.findElement(By.id("textinput-cep")).click();
    driver.findElement(By.id("textinput-cep")).sendKeys("40.270-240");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.id("textinput-endereco")).click();
    driver.findElement(By.id("textinput-complemento")).click();
    driver.findElement(By.id("textinput-complemento")).sendKeys("575");
    driver.findElement(By.id("btn_crud_post41107")).click();
  }
}
