// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CriarMarcaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.addArguments("--headless");
    chromeOptions.addArguments("--no-sandbox");
    driver = new ChromeDriver(chromeOptions);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void criarMarca() {
    driver.get("https://app-13-74-22129.ide.cronapp.io/#/home");
    driver.manage().window().setSize(new Dimension(958, 1039));
    driver.findElement(By.cssSelector(".dropdown:nth-child(6) > .dropdown-toggle > span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".dropdown-menu > li:nth-child(1) span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".k-grid-add")).click();
    driver.findElement(By.id("f8fe")).click();
    driver.findElement(By.id("f8fe")).sendKeys("Alimentos");
    driver.findElement(By.cssSelector(".k-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".k-alt:nth-child(4) .k-grid-delete"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("fd81")).click();
  }
}
